---
title: "Reporte"
author: "Pablo Aguirre Hörmann"
date: "12/25/2021"
output: 
  officedown::rdocx_document:
    reference_docx: Formato.docx
params:
    reg: DE VALPARAISO
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(readr)
library(dplyr)
library(stringr)
library(ggplot2)
library(flextable)
library(officedown)
library(chilemapas)
```

```{r cars}
datos_votaciones_pob <- read_csv("../0.datos/BBDDComuna.csv")
datos_reg <- datos_votaciones_pob %>% 
  filter(region == params$reg)
```

El reporte...

```{r}
datos_votaciones_pob %>% 
  group_by(region) %>% 
  summarise(
    vot_tot = sum(vot_tot, na.rm = TRUE),
    padron = sum(padron, na.rm = TRUE),
    orden_reg = mean(orden_reg)
  ) %>% 
  rowwise() %>% 
  mutate(participacion = paste0(round(vot_tot/padron,3)*100, "%"),
         participacion = str_replace_all(participacion, "\\.", ","),
         region = str_remove_all(region, "DE "),
         region = str_remove_all(region, "DEL "),
         region = str_to_title(region)) %>% 
  arrange(orden_reg) %>% 
  select(-orden_reg) %>% 
  rename(
    "Región" = region,
    "N° de votantes" = vot_tot,
    "Tamaño del padrón" = padron,
    "Participación (%)" = participacion
  ) %>% 
  flextable() %>% 
  theme_box() %>% 
  colformat_num(big.mark = ".", decimal.mark = ",") %>% 
  width(j = c(1,2,3,4), width = c(2.5,1.3,1.3,1.3)) %>% 
  fontsize(size = 9, part = "all") %>% 
  align(align = "center", part = "all") %>% 
  padding(padding = 0, part = "all")
```

# Relación entre participación y pobreza

El siguiente gráfico muestra...

```{r}
datos_reg %>% 
  ggplot(aes(x = per_pob2020, y = participacion)) +
  geom_point(size = 1, col = "grey") +
  geom_smooth(method = "lm", se = FALSE, col = "red") +
  theme_minimal() +
  labs(x = "% Pobreza 2020 (ingresos)",
       y = "% de participación",
       title = "Cambio en participación según nivel de pobreza")
```

# Mapa

```{r}
mapa_comunas %>% 
  mutate(codigo_comuna = as.numeric(codigo_comuna)) %>% 
  left_join(datos_votaciones_pob, by = c("codigo_comuna" = "cod_casen")) %>% 
  filter(com_nom != "ISLA DE PASCUA") %>% 
  filter(region == params$reg) %>% 
  ggplot(aes(geometry = geometry, 
             fill = participacion)) +
  geom_sf() +
  scale_fill_gradientn(name = "Participación", colours = c("red", "green")) +
  theme_minimal() +
  labs(x = NULL, y = NULL)
```

